// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgiyhrfamrfftefvoqqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnaXlocmZhbXJmZnRlZnZvcXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzYxNzEsImV4cCI6MjA3MTIxMjE3MX0.fMF6x59MBzMLtjl8kmVHABRERoOjlg7l4O9y5FBt6w0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});